# Generated by Django 6.0.6 on 2026-07-05 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='slug',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['profession', 'order'], name='paths_step_profess_4c4c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='stepitem',
            index=models.Index(fields=['step', 'order'], name='paths_stepi_step_id_2d3689_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['user', 'completed'], name='paths_userp_user_id_88fbd1_idx'),
        ),
        migrations.AddIndex(
            model_name='userprogress',
            index=models.Index(fields=['step_item', 'completed'], name='paths_userp_step_it_f5e517_idx'),
        ),
    ]
