# Generated by Django 6.0.6 on 2026-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_subscription_is_active_alter_subscription_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, help_text='Reusable card auth code (auth_xxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_customer_code',
            field=models.CharField(blank=True, help_text='Paystack customer reference (cus_xxx)', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_email',
            field=models.EmailField(blank=True, help_text='Email used for Paystack transactions', max_length=254),
        ),
        migrations.AddField(
            model_name='subscription',
            name='paystack_subscription_code',
            field=models.CharField(blank=True, help_text='Paystack subscription reference (sub_xxx)', max_length=100),
        ),
    ]
