# Generated by Django 6.0.6 on 2026-07-04 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('shopify', 'Shopify'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('etsy', 'Etsy'), ('square', 'Square')], max_length=20)),
                ('label', models.CharField(blank=True, help_text='Friendly name for this connection', max_length=100)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, max_length=200)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_email', models.EmailField(blank=True, max_length=200)),
                ('metadata', models.TextField(blank=True, help_text='JSON blob for platform-specific data')),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform', 'account_name'],
                'unique_together': {('user', 'platform', 'account_id')},
            },
        ),
    ]
