# Generated by Django 6.0.6 on 2026-07-05 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='platformconnection',
            name='platform',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('shopify', 'Shopify'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('etsy', 'Etsy'), ('square', 'Square')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['user', 'is_active'], name='connections_user_id_3764b0_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['platform', 'is_active'], name='connections_platfor_91a3f6_idx'),
        ),
        migrations.AddIndex(
            model_name='platformconnection',
            index=models.Index(fields=['user', 'last_synced_at'], name='connections_user_id_a55b62_idx'),
        ),
    ]
