import os, django
os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings'
django.setup()
from ideas.models import Idea

Idea.objects.all().delete()

ideas = [
    {
        'title': 'Micro-SaaS for Payroll Tax Compliance',
        'description': 'Automated tax filing tool for remote-first startups.',
        'long_description': 'Remote work created a nightmare for payroll tax compliance. Companies now need to track and file taxes in multiple states for each remote employee. This SaaS automates filing. Market growing 25% YoY.',
        'industry': 'fintech',
        'market_demand': 94,
        'ease_of_entry': 'medium',
        'risk_level': 'medium',
        'profit_range_min': 250000,
        'profit_range_max': 1000000,
        'monthly_revenue_min': 20000,
        'monthly_revenue_max': 80000,
        'startup_cost_min': 5000,
        'startup_cost_max': 15000,
        'time_to_revenue': 4,
        'time_to_profit': 8,
        'growth_potential': 88,
        'why_now': 'Remote work is permanent. 74% of companies plan to stay remote. Current solutions are expensive enterprise tools.',
        'steps_to_start': 'Research remote tax compliance laws\nBuild MVP for single-state tax calculation\nGet 3 beta users (offer free first year)\nIntegrate with Gusto/ADP APIs\nLaunch with 2-state support',
        'key_metrics': 'MRR (monthly recurring revenue)\nChurn rate < 3%\nCustomer acquisition cost (CAC)\nNet promoter score (NPS)',
        'icon': 'currency_exchange',
    },
    {
        'title': 'Hyper-Local Solar Maintenance',
        'description': 'Subscription maintenance service for residential solar panels in your city.',
        'long_description': 'Solar panel owners need regular cleaning and inspection. Most installers don\'t offer ongoing maintenance. Recurring revenue, booming demand.',
        'industry': 'energy',
        'market_demand': 82,
        'ease_of_entry': 'easy',
        'risk_level': 'low',
        'profit_range_min': 50000,
        'profit_range_max': 200000,
        'monthly_revenue_min': 4000,
        'monthly_revenue_max': 16000,
        'startup_cost_min': 2000,
        'startup_cost_max': 8000,
        'time_to_revenue': 1,
        'time_to_profit': 3,
        'growth_potential': 75,
        'why_now': 'Solar installations hit record highs. Most homeowners have no maintenance plan. Panels lose 20% efficiency without cleaning.',
        'steps_to_start': 'Get equipment (ladder, cleaning tools, multimeter)\nGet liability insurance ($500-1000/yr)\nCreate website with service packages\nPartner with 3 local solar installers\nStart with 10 customers in your neighborhood',
        'key_metrics': 'Customers per route (efficiency)\nRecurring revenue per customer\nCustomer lifetime value (LTV)\nReferral rate',
        'icon': 'solar_power',
    },
    {
        'title': 'AI-Powered ADHD Career Coaching',
        'description': 'Coaching platform for neurodivergent professionals seeking career growth.',
        'long_description': 'ADHD adults face unique workplace challenges. This platform combines AI tools with human coaching from ADHD-specialized coaches. Massively underserved market.',
        'industry': 'health',
        'market_demand': 89,
        'ease_of_entry': 'medium',
        'risk_level': 'medium',
        'profit_range_min': 100000,
        'profit_range_max': 500000,
        'monthly_revenue_min': 8000,
        'monthly_revenue_max': 40000,
        'startup_cost_min': 3000,
        'startup_cost_max': 10000,
        'time_to_revenue': 2,
        'time_to_profit': 5,
        'growth_potential': 82,
        'why_now': '8 million US adults have ADHD. Corporate DEI programs now include neurodiversity. No dedicated ADHD career platform exists.',
        'steps_to_start': 'Get certified as ADHD coach or partner with one\nBuild website with assessment quiz\nCreate 3 video courses\nLaunch on Instagram/TikTok\nOffer first 10 sessions at 50% off',
        'key_metrics': 'Coaching session conversion rate\nClient outcome scores\nCourse completion rate\nMonthly active users',
        'icon': 'psychology',
    },
    {
        'title': 'Local Freelancer Marketplace',
        'description': 'Curated platform connecting local businesses with vetted freelancers in your city.',
        'long_description': 'Upwork is great for remote work, but local businesses need freelancers who can show up. This platform vets freelancers and focuses on in-person local work.',
        'industry': 'fintech',
        'market_demand': 78,
        'ease_of_entry': 'medium',
        'risk_level': 'medium',
        'profit_range_min': 60000,
        'profit_range_max': 300000,
        'monthly_revenue_min': 5000,
        'monthly_revenue_max': 25000,
        'startup_cost_min': 5000,
        'startup_cost_max': 20000,
        'time_to_revenue': 3,
        'time_to_profit': 7,
        'growth_potential': 70,
        'why_now': 'Local businesses prefer working with people they can meet. Remote platforms take 20% fees. Only 2-3 cities have local platforms.',
        'steps_to_start': 'Identify top 5 freelance categories in your city\nRecruit 20 freelancers per category\nBuild marketplace platform\nGet 5 local businesses as beta buyers\nTake 10% commission',
        'key_metrics': 'Completed gigs per month\nGross merchandise volume (GMV)\nFreelancer retention rate\nBuyer repeat rate',
        'icon': 'groups',
    },
    {
        'title': 'Eco-Friendly Home Cleaning',
        'description': 'Subscription cleaning service using only biodegradable, non-toxic products.',
        'long_description': 'Consumers avoid harsh chemicals. Parents, pet owners, health-conscious people want clean homes without toxic residue. Premium eco-friendly positioning.',
        'industry': 'health',
        'market_demand': 85,
        'ease_of_entry': 'easy',
        'risk_level': 'low',
        'profit_range_min': 40000,
        'profit_range_max': 150000,
        'monthly_revenue_min': 3000,
        'monthly_revenue_max': 12000,
        'startup_cost_min': 1000,
        'startup_cost_max': 5000,
        'time_to_revenue': 0,
        'time_to_profit': 1,
        'growth_potential': 68,
        'why_now': 'Eco-friendly product market grew 25% in 2024. Parents actively seek non-toxic services. Subscription economy is normalized.',
        'steps_to_start': 'Source eco-friendly supplies in bulk\nCreate 3 subscription tiers\nGet liability insurance\nBuild simple booking website\nStart on Nextdoor for marketing',
        'key_metrics': 'Customers per cleaner\nRecurring revenue per customer\nProduct cost per clean\nCancellation rate',
        'icon': 'cleaning_services',
    },
    {
        'title': 'Senior Tech Support Service',
        'description': 'In-home and remote tech support tailored for seniors and elderly users.',
        'long_description': 'Seniors struggle with smartphones, smart TVs, video calls, online banking. Family is often too busy to help. Patient in-person tech support for elderly.',
        'industry': 'health',
        'market_demand': 92,
        'ease_of_entry': 'easy',
        'risk_level': 'low',
        'profit_range_min': 35000,
        'profit_range_max': 120000,
        'monthly_revenue_min': 3000,
        'monthly_revenue_max': 10000,
        'startup_cost_min': 500,
        'startup_cost_max': 2000,
        'time_to_revenue': 0,
        'time_to_profit': 1,
        'growth_potential': 90,
        'why_now': '10,000 Americans turn 65 daily. Technology gets more complex. Senior living facilities need tech support. No national brand dominates.',
        'steps_to_start': 'Create simple one-page website\nPartner with 2 senior living facilities\nPrint flyers for community centers\nOffer first session free\nCreate simple visual guides',
        'key_metrics': 'Sessions per week\nCustomer referral rate\nRecurring subscription rate\nCustomer satisfaction score',
        'icon': 'support_agent',
    },
    {
        'title': 'Local Food Waste Composting',
        'description': 'Subscription compost pickup for households and restaurants.',
        'long_description': 'Most cities don\'t offer residential compost pickup. Environmentally conscious households want to reduce landfill waste. Low overhead, recurring revenue.',
        'industry': 'energy',
        'market_demand': 76,
        'ease_of_entry': 'easy',
        'risk_level': 'low',
        'profit_range_min': 30000,
        'profit_range_max': 100000,
        'monthly_revenue_min': 2500,
        'monthly_revenue_max': 8000,
        'startup_cost_min': 3000,
        'startup_cost_max': 10000,
        'time_to_revenue': 1,
        'time_to_profit': 4,
        'growth_potential': 72,
        'why_now': 'Food waste is 25% of landfill content. Cities are starting to mandate composting (California SB 1383). First movers win.',
        'steps_to_start': 'Secure composting site\nBuy 50 buckets with lids\nGet a pickup truck or trailer\nCreate simple website\nStart with 20 households',
        'key_metrics': 'Pounds diverted per customer\nCustomer retention rate\nRoute efficiency\nCost per pound collected',
        'icon': 'cycle',
    },
    {
        'title': 'Kids Coding & Robotics Classes',
        'description': 'After-school coding classes for ages 7-14 with robotics kits.',
        'long_description': 'Parents want kids to learn coding but school programs are inadequate. In-person classes where kids build and program robots. Small classes, project-based.',
        'industry': 'edtech',
        'market_demand': 88,
        'ease_of_entry': 'medium',
        'risk_level': 'low',
        'profit_range_min': 40000,
        'profit_range_max': 180000,
        'monthly_revenue_min': 3000,
        'monthly_revenue_max': 15000,
        'startup_cost_min': 2000,
        'startup_cost_max': 8000,
        'time_to_revenue': 1,
        'time_to_profit': 3,
        'growth_potential': 78,
        'why_now': 'STEM education spending grows 15% annually. Parents pay $30-50 per class. Remote learning created demand for in-person enrichment.',
        'steps_to_start': 'Buy 10 robotics kits ($50 each)\nDevelop 4 age-group curriculums\nRent community center room ($20-40/hr)\nCreate website with schedule\nOffer free trial class',
        'key_metrics': 'Students per class\nClass utilization rate\nReferral rate\nRevenue per student',
        'icon': 'code',
    },
    {
        'title': 'Personalized Nutrition Meal Prep',
        'description': 'Meal prep tailored to dietary needs and health goals using AI recommendations.',
        'long_description': 'Generic meal prep is boring. This uses an AI quiz to personalize weekly meals. Local kitchen, fresh ingredients, higher value than generic services.',
        'industry': 'health',
        'market_demand': 86,
        'ease_of_entry': 'medium',
        'risk_level': 'medium',
        'profit_range_min': 60000,
        'profit_range_max': 250000,
        'monthly_revenue_min': 5000,
        'monthly_revenue_max': 20000,
        'startup_cost_min': 10000,
        'startup_cost_max': 30000,
        'time_to_revenue': 2,
        'time_to_profit': 6,
        'growth_potential': 80,
        'why_now': '50% of Americans want personalized nutrition. AI makes personalization scalable. Local/fresh beats shipped/frozen. Generic services have high churn.',
        'steps_to_start': 'Rent commercial kitchen ($20-30/hr)\nDevelop 20 base recipes\nBuild quiz website\nBuy packaging supplies\nStart with 10 customers',
        'key_metrics': 'Orders per week\nAverage order value\n90-day retention rate\nFood cost percentage',
        'icon': 'restaurant',
    },
]

for data in ideas:
    Idea.objects.create(**data)

print(f'Seeded {Idea.objects.count()} rich ideas')
