# Generated by Django 6.0.6 on 2026-07-04 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('freelancer', 'Freelancer'), ('retail', 'Retail'), ('service', 'Service'), ('food', 'Food'), ('creator', 'Creator')], default='freelancer', max_length=20)),
                ('trial_uses_remaining', models.IntegerField(default=3)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
