# Generated by Django 6.0.6 on 2026-07-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD ($) - US Dollar'), ('EUR', 'EUR (€) - Euro'), ('GBP', 'GBP (£) - British Pound'), ('JPY', 'JPY (¥) - Japanese Yen'), ('CNY', 'CNY (¥) - Chinese Yuan'), ('INR', 'INR (₹) - Indian Rupee'), ('CAD', 'CAD ($) - Canadian Dollar'), ('AUD', 'AUD ($) - Australian Dollar'), ('BRL', 'BRL (R$) - Brazilian Real'), ('MXN', 'MXN ($) - Mexican Peso'), ('KRW', 'KRW (₩) - South Korean Won'), ('SGD', 'SGD ($) - Singapore Dollar'), ('HKD', 'HKD ($) - Hong Kong Dollar'), ('CHF', 'CHF (Fr) - Swiss Franc'), ('SEK', 'SEK (kr) - Swedish Krona'), ('NOK', 'NOK (kr) - Norwegian Krone'), ('DKK', 'DKK (kr) - Danish Krone'), ('NZD', 'NZD ($) - New Zealand Dollar'), ('ZAR', 'ZAR (R) - South African Rand'), ('TRY', 'TRY (₺) - Turkish Lira'), ('RUB', 'RUB (₽) - Russian Ruble'), ('PLN', 'PLN (zł) - Polish Zloty'), ('THB', 'THB (฿) - Thai Baht'), ('IDR', 'IDR (Rp) - Indonesian Rupiah'), ('MYR', 'MYR (RM) - Malaysian Ringgit'), ('PHP', 'PHP (₱) - Philippine Peso'), ('AED', 'AED (د.إ) - UAE Dirham'), ('SAR', 'SAR (﷼) - Saudi Riyal'), ('ILS', 'ILS (₪) - Israeli Shekel'), ('VND', 'VND (₫) - Vietnamese Dong'), ('NGN', 'NGN (₦) - Nigerian Naira'), ('KES', 'KES (KSh) - Kenyan Shilling'), ('EGP', 'EGP (E£) - Egyptian Pound'), ('PKR', 'PKR (₨) - Pakistani Rupee'), ('BDT', 'BDT (৳) - Bangladeshi Taka')], default='USD', max_length=5),
        ),
    ]
