# Generated by Django 6.0.6 on 2026-07-05 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(choices=[('freelancer', 'Freelancer'), ('retail', 'Retail'), ('service', 'Service'), ('food', 'Food'), ('creator', 'Creator')], db_index=True, default='freelancer', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_status',
            field=models.CharField(db_index=True, default='free', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user', 'profession'], name='accounts_us_user_id_da12ee_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['subscription_status', 'profession'], name='accounts_us_subscri_d0da43_idx'),
        ),
    ]
