# Generated by Django 6.0.6 on 2026-07-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('industry', models.CharField(choices=[('fintech', 'FinTech & SaaS'), ('energy', 'Sustainable Energy'), ('health', 'Health & Wellness'), ('edtech', 'EdTech')], max_length=20)),
                ('market_demand', models.IntegerField(help_text='Percentage 0-100')),
                ('ease_of_entry', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('profit_range_min', models.IntegerField(help_text='Min profit in USD')),
                ('profit_range_max', models.IntegerField(help_text='Max profit in USD')),
                ('icon', models.CharField(default='currency_exchange', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
