# Generated by Django 6.0.6 on 2026-07-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='growth_potential',
            field=models.IntegerField(default=50, help_text='Long-term growth score 0-100'),
        ),
        migrations.AddField(
            model_name='idea',
            name='key_metrics',
            field=models.TextField(blank=True, help_text='KPIs to track (one per line)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full analysis text'),
        ),
        migrations.AddField(
            model_name='idea',
            name='monthly_revenue_max',
            field=models.IntegerField(default=0, help_text='Est. monthly revenue max'),
        ),
        migrations.AddField(
            model_name='idea',
            name='monthly_revenue_min',
            field=models.IntegerField(default=0, help_text='Est. monthly revenue min'),
        ),
        migrations.AddField(
            model_name='idea',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='idea',
            name='startup_cost_max',
            field=models.IntegerField(default=0, help_text='Max startup cost in USD'),
        ),
        migrations.AddField(
            model_name='idea',
            name='startup_cost_min',
            field=models.IntegerField(default=0, help_text='Min startup cost in USD'),
        ),
        migrations.AddField(
            model_name='idea',
            name='steps_to_start',
            field=models.TextField(blank=True, help_text='Key steps to launch (one per line)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='time_to_profit',
            field=models.IntegerField(default=6, help_text='Months to profitability'),
        ),
        migrations.AddField(
            model_name='idea',
            name='time_to_revenue',
            field=models.IntegerField(default=3, help_text='Months to first revenue'),
        ),
        migrations.AddField(
            model_name='idea',
            name='why_now',
            field=models.TextField(blank=True, help_text='Why this is a good time for this idea'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='profit_range_max',
            field=models.IntegerField(help_text='Max yearly profit in USD'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='profit_range_min',
            field=models.IntegerField(help_text='Min yearly profit in USD'),
        ),
    ]
