# Generated by Django 6.0.6 on 2026-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_enhanced_idea_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='ease_of_entry',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='idea',
            name='industry',
            field=models.CharField(choices=[('fintech', 'FinTech & SaaS'), ('energy', 'Sustainable Energy'), ('health', 'Health & Wellness'), ('edtech', 'EdTech')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='idea',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=10),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['industry', 'is_active'], name='ideas_idea_industr_e08e89_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['risk_level', 'is_active'], name='ideas_idea_risk_le_0ef88d_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['ease_of_entry', 'is_active'], name='ideas_idea_ease_of_d80be2_idx'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['startup_cost_min', 'is_active'], name='ideas_idea_startup_b6bf83_idx'),
        ),
    ]
