# Generated by Django 6.0.6 on 2026-07-05 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='is_balanced',
            field=models.BooleanField(db_index=True, editable=False),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', '-created_at'], name='reconciliat_user_id_021af2_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'is_balanced'], name='reconciliat_user_id_43fe55_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['user', 'created_at'], name='reconciliat_user_id_4498b9_idx'),
        ),
    ]
